' Copyright 2017, 2018, 2022 Reahl Software Services (Pty) Ltd. All rights reserved.

@startuml
!include ../../../base.iuml
show members
skinparam class {
 BorderColor Black
}

title Workflow Action and Requirement

class DeferredAction{
	deadline
	success_action()
	deadline_action()
}


DeferredAction "*" -right- Requirement : < deferred_actions
DeferredAction -- "*" Requirement : requirements >

@enduml
