' Copyright 2017, 2018, 2022 Reahl Software Services (Pty) Ltd. All rights reserved.

@startuml
!include ../../../base.iuml

title Workflow Inbox

Inbox "*" --right- "*" Queue
Queue "1" --right-- "*" Task
Task "*" -down- "0..1" Party : reserved_by >

@enduml
