' Copyright 2017, 2018, 2022 Reahl Software Services (Pty) Ltd. All rights reserved.

@startuml
!include ../../../../../base.iuml

title Invoking server-side methods from a browser

SubResource -up-|> Resource
RemoteMethod -up-|> SubResource
CheckedRemoteMethod -up-|> RemoteMethod
EventChannel -up-|> RemoteMethod

RemoteMethod -right- MethodResult
JsonResult -up-|> MethodResult
WidgetResult -up-|> MethodResult
RedirectAfterPost -up-|> MethodResult
noRedirectAfterPost -up-|> MethodResult

@enduml
