' Copyright 2017, 2018, 2022 Reahl Software Services (Pty) Ltd. All rights reserved.

@startuml
!include ../../../../base.iuml

title How composed pages work

ComposedPage -up-|> Resource

UrlBoundView .up.|> View
View -right- UserInterface : < current_view

ComposedPage -right- UrlBoundView
ComposedPage -- Widget_ : main_window >

UrlBoundView -- "*" WidgetFactory : slot_definitions >

Widget_ -right- WidgetFactory : default_slot_definitions
Widget -up-> WidgetFactory
Widget -- "*" Widget : children
Widget_ -- "*" Widget : {per slot} slot_contents

@enduml
