' Copyright 2016, 2018, 2022 Reahl Software Services (Pty) Ltd. All rights reserved.

@startuml
!include ../../../../base.iuml

title Different views

PseudoView -up-|> View
UrlBoundView -up-|> View
FileView -up-|> View

RedirectView -up-|> UrlBoundView

NoView -up-|> PseudoView
UserInterfaceRootRedirectView -up-|> PseudoView


@enduml
