' Copyright 2017, 2018, 2022 Reahl Software Services (Pty) Ltd. All rights reserved.

@startuml
!include ../../../../base.iuml

title Pagination

'│ is ascii-179



@startsalt
{+

{
<i><b>PageMenu</b></i>
│< < 1 2 3 4 5 > >│
}
.
<i><b>PagedPanel</b></i>
{+
.
.
Current page contents
being displayed here
.
.
}


}
@endsalt

@enduml
