' Copyright 2017, 2018, 2022 Reahl Software Services (Pty) Ltd. All rights reserved.

@startuml
!include ../../../../base.iuml

title Pagination

class "<b>Menu</b>" as Menu
class "<b>PageMenu</b>" as PageMenu{
	query_fields
}
note top: page number selector

class "<b>PagedPanel</b>" as PagedPanel{
	query_fields
}
note right: current page contents \nbeing displayed

class "<b>PageIndex</b>" as PageIndex{
	current_page_number
	start_page_number
}
note left of PageIndex : does all the calculations \nneeded by the \nparticipating Widgets
Widget <|--- PageMenu
Widget <|--- PagedPanel

PageMenu -right- PagedPanel : pagedPanel >
PageMenu -left- Menu : html_representation >
PageMenu -- PageIndex
PageIndex -- PagedPanel
PageIndex -right- Page
PageIndex <|-- AnnualPageIndex
PageIndex <|-- SequentialPageIndex

@enduml
