@startuml

title Building packages and distributing them to remote repositories

hide members
hide circle

EggProject -right- "*" DistributionPackage : packages >
DistributionPackage -right- "*" RemoteRepository : repositories >

@enduml