@startuml
!include base.iuml

title Building packages and distributing them to remote repositories

EggProject -right- "*" DistributionPackage : packages >
DistributionPackage -right- "*" RemoteRepository : repositories >

@enduml