' Copyright 2017, 2018, 2022 Reahl Software Services (Pty) Ltd. All rights reserved.

@startuml
!include ../../../base.iuml

title Building packages and distributing them to remote repositories

EggProject -right- "*" DistributionPackage : packages >
DistributionPackage -right- "*" RemoteRepository : repositories >

@enduml
