@startuml
!include ../../../base.iuml

title Egg and chicken projects - development environment

EggProject -left- "*" Dependency
Dependency <|-- ThirdPartyDependency

EggProject <|-- ChickenProject
ChickenProject -- "*" EggProject
EggProject -- EntryPointExport
EntryPointExport <|--- ReahlEggExport
EntryPointExport <|.. "?"
ReahlEggExport .right. ReahlEgg : {refers indirectly to}

@enduml