' Copyright 2017, 2018, 2022 Reahl Software Services (Pty) Ltd. All rights reserved.

@startuml
!include ../../../base.iuml

title Projects and project related metadata

Project <|-- EggProject
Dependency <|-- ThirdpartyDependency
EggProject -left- Dependency : build_deps >
EggProject -- Dependency : test_deps >
EggProject -- Dependency : run_deps >

Project -right- ProjectMetadata : metadata
Project -- SourceControlSystem : source_control
SourceControlSystem <|-- BzrSourceControl
SourceControlSystem <|-- GitSourceControl
ProjectMetadata <|-- DebianPackageMetadata
ProjectMetadata <|-- HardcodedMetadata

@enduml
