' Copyright 2017, 2018, 2022 Reahl Software Services (Pty) Ltd. All rights reserved.

@startuml
!include ../../../base.iuml

title Projects and Workspace

class "<b>Project</b>" as Project
class "<b>Workspace</b>" as Workspace

Project "*" -right- Workspace
(Project, Workspace) .. ProjectList
LocalRepository <|-- LocalAptRepository
Workspace -right- LocalRepository : distribution_egg_repository
Workspace -- LocalAptRepository : distribution_apt_repository

@enduml
