@startuml

title Projects and Workspace

hide members
hide circle

class Project #red
class Workspace #red

Project "*" -right- Workspace
(Project, Workspace) .. ProjectList
LocalRepository <|-- LocalAptRepository
Workspace -right- LocalRepository : distribution_egg_repository
Workspace -- LocalAptRepository : distribution_apt_repository

@enduml