[build-system]
requires = [
  "setuptools >= 68",
  "wheel",
  "setuptools-git >= 1.1",
  "pytest-runner",
  "toml",
  "reahl-component-metadata >= 7.0.0"
  ]
build-backend = "setuptools.build_meta"

[project]
name = "i18nexample"
version = "0.1"
requires-python = ">=3.8"
dependencies = [
  "reahl-web>=7.0,<7.1",
  "reahl-component>=7.0,<7.1",
  "reahl-web-declarative>=7.0,<7.1",
  "reahl-sqlitesupport>=7.0,<7.1"
  ]
authors = [ 
  {name = "Iwan Vosloo", email = "iwan@reahl.org"},
  {name = "Craig Sparks", email = "craig@reahl.org"}
]

[project.entry-points."reahl.translations"]
i18nexample = "i18nexamplemessages"

[tool.setuptools]
py-modules = ["i18nexample"]

[tool.setuptools.packages.find]
exclude = ["etc", "build", "dist"]

[tool.reahl-component]
