
'skinparam handwritten true
'skinparam roundcorner 15

skinparam note {
 BackgroundColor LightGray
 BorderColor Silver
}

skinparam class {
 BackgroundColor #ffffee
 ArrowColor #909066
 BorderColor #909066
}

skinparam object {
 BorderColor #909066ff
 ArrowColor #909066
 BorderColor #909066
}

skinparam sequence {
 ParticipantBackgroundColor #ffffee
 ParticipantBorderColor #909066
}

skinparam component {
 BackgroundColor #ffffee
 BorderColor Black
 CollectionsBorderColor #909066
}

skinparam interface {
  BackgroundColor #ffffee
  borderColor Black
}

 'hide methods
 hide members
 hide circle

