@startuml

title Fixtures

hide methods
hide circle

class ContextAwareFixture {
}

class ReahlSystemSessionFixture <<session-scoped>> {
	context
	config
	reahl_system
	system_control
}

class ReahlSystemFixture {
	context
        @system_control
	config
}


class SqlAlchemyFixture {
      persistent_test_classes
      start_transaction()
      finalise_transaction()
}


class WebServerFixture <<session-scoped>> {
	reahl_server
	web_driver
	driver_browser
	firefox_driver
	chrome_driver
}

class WebFixture {
      request
      view
      current_location
      wsgi_app
      user_interface
      driver_browser
      log_in()
}


class PartyAccountFixture {
      session
      party
      system_account
}



ContextAwareFixture <|-- ReahlSystemSessionFixture
ContextAwareFixture <|-- ReahlSystemFixture
ReahlSystemSessionFixture <-left- ReahlSystemFixture 

ReahlSystemFixture <-- SqlAlchemyFixture 
WebServerFixture -up-> ReahlSystemSessionFixture

ReahlSystemFixture <-- WebFixture
SqlAlchemyFixture <-- WebFixture
WebServerFixture <-- WebFixture
PartyAccountFixture <-- WebFixture


ReahlSystemFixture <-- PartyAccountFixture
SqlAlchemyFixture <-- PartyAccountFixture



@enduml
