' Copyright 2017, 2018, 2022 Reahl Software Services (Pty) Ltd. All rights reserved.

@startuml
!include ../../../base.iuml

title Action

class callable <<interface>>

AdaptedMethod <|-- Action
AccessRights -right- Action : readable
AccessRights -right- Action : writable
AdaptedMethod -right-> callable

@enduml
