@startuml
!include base.iuml

title Action

class callable <<interface>>

AdaptedMethod <|-- Action
AccessRights -right- Action : readable
AccessRights -right- Action : writable
AdaptedMethod -right-> callable

@enduml