' Copyright 2017, 2018, 2022 Reahl Software Services (Pty) Ltd. All rights reserved.

@startuml
!include ../../../base.iuml

title Database components

note as N1
   Use the system-wide SystemControl to control any database
   related operations. It keeps an ORMControl for the ORM in use,
   and a DatabaseControl for the database in use.

   The ReahlSystemConfig specifies which ORMControl to use and from
   its connection_uri we deduce which DatabaseControl to use.

   Subclasses are written for supporting specific ORMs or Database
   backends.

   Find the SystemControl from the current ExecutionContext.
end note

class ExecutionContext
class "<b>SystemControl</b>" as SystemControl
class Configuration
class ReahlSystemConfig
class "<b>ORMControl</b>" as ORMControl
class "<b>DatabaseControl</b>" as DatabaseControl

ExecutionContext -down- SystemControl
SystemControl -down- DatabaseControl
SystemControl -down- ORMControl

Configuration <|-- ReahlSystemConfig
ReahlSystemConfig -- ORMControl

@enduml
