' Copyright 2017, 2018, 2022 Reahl Software Services (Pty) Ltd. All rights reserved.

@startuml
!include ../../../base.iuml

title Fields and field metadata

Field -left- object : storage_object >
Field -- ValidationConstraintList
ValidationConstraintList -down- ValidationConstraint
Field -right- AccessRights
AccessRights -right- Action : readable
AccessRights -right- Action : writable

@enduml
