' Copyright 2018, 2022 Reahl Software Services (Pty) Ltd. All rights reserved.

@startuml
!include ./../../../base.iuml

title Fields and Events 

note as N1
  A Field controls the attribute of a model object.
  A Field can have ValidationConstraints and AccessRights. 
  An Event is a kind of Field representing something the user can trigger.
  Events are made to do something by linking them to Actions.
  Actions wrap a python callable
  An AccessRights is linked to one Action to determine whether the 
  Field it belongs to is writeable; AccessRights is linked to another
  another Action to determine if it is readable.
end note


callable <<python>>
attribute <<python>>
Exception <<python>>

Event --up-|> Field
Event -- Action
Action --> callable : "function or object method"

Field --> attribute : domain_value
Field --> ModelObject : "bound to"
ModelObject -right-> attribute: "has attribute"
Field -right- "*" ValidationConstraint
Field --- AccessRights
AccessRights -left- Action : readable
AccessRights -left- Action : writable

ValidationConstraint --up-|> Exception


@enduml
