' Copyright 2017, 2018 Reahl Software Services (Pty) Ltd. All rights reserved.

@startuml
!include base.iuml

title Reahl commandline shells

ReahlCommandLine -right- “*” Command : {discovered via entrypoints}
Command <|-- ProductionCommand
ReahlCommandLine <|-- ProductionCommandLine
ProductionCommandLine -right- "*" ProductionCommand
ProductionCommand -- SystemControl
ProductionCommand -- Configuration

@enduml
