' Copyright 2016, 2018, 2022 Reahl Software Services (Pty) Ltd. All rights reserved.

@startuml
!include ../../../../base.iuml

title Controllers zoomed out

UrlBoundView -up-|> View
UrlBoundView .right. ViewFactory : matches >
View .right. Controller
UserInterface -left- Controller
ViewPseudoFactory -up-|> ViewFactory
Controller -- "*" EventHandler
Event .right. "*" EventHandler
Transition -up-|> EventHandler
Transition -left- ViewFactory : source
EventHandler -- ViewFactory : target


@enduml
