' Copyright 2016, 2018, 2022 Reahl Software Services (Pty) Ltd. All rights reserved.

@startuml
!include ../../../../base.iuml

title Controllers zoomed in

class set <<python>>

Controller -- EventHandlerList
set <|-down- FactoryDict
Controller -right- FactoryDict
FactoryDict .right. FactoryFromUrlRegex

FactoryFromUrlRegex .right.> View : creates
ViewFactory -up-|> FactoryFromUrlRegex


@enduml
