' Copyright 2017, 2018, 2022 Reahl Software Services (Pty) Ltd. All rights reserved.

@startuml
!include ../../../../base.iuml

title Getting the current locale urlpath


package reahl.component{
	class ExecutionContext
	class Configuration
}

package reahl.webdeclarative{
	class UserSession
}

package reahl.web{
	class UserSessionProtocol
	class Request
	class Url{
		locale_path
	}
}



ExecutionContext -right- Configuration
ExecutionContext -- Request
Request -right- Url : current_url
UserSessionProtocol <-[dotted]- UserSession
UserSession -- ExecutionContext




@enduml
