
@startuml

title Getting the current locale urlpath

'hide members
hide methods
hide circle


package reahl.component{
	class ExecutionContext
	class Configuration
}

package reahl.webdeclarative{
	class UserSession
}

package reahl.web{
	class UserSessionProtocol
	class Request
	class Url{
		locale_path
	}
}



ExecutionContext -right- Configuration
ExecutionContext -- Request
Request -right- Url : current_url
UserSessionProtocol <-[dotted]- UserSession
UserSession -- ExecutionContext




@enduml
