' Copyright 2017, 2018, 2022 Reahl Software Services (Pty) Ltd. All rights reserved.

@startuml
!include ../../../../base.iuml

title Including frontend library static resources on pages


HTML5Page -right- Head
HTML5Page -- Body

Head -right- HeaderContent : reahl_header
Body -right- FooterContent : real_footer

HeaderContent -right- LibraryIndex
FooterContent -- LibraryIndex

WebConfig -down- LibraryIndex : frontend_libraries >
LibraryIndex -down- "*" Library

@enduml
