' Copyright 2017, 2018, 2022 Reahl Software Services (Pty) Ltd. All rights reserved.

@startuml
!include ../../../../base.iuml

title Basics of remote methods

hide footbox

note left of ReahlWSGIApp: 	wsgi requests are handled inside\n a ReahlWSGIApp by \ncreating the appropriate Resource\n and using it to return a Response


-> ReahlWSGIApp : request
ReahlWSGIApp -> ReahlWSGIApp : ""resource_for(request)""
create Resource
ReahlWSGIApp -> Resource
ReahlWSGIApp -> Resource : ""handle_request(request)""
create Response
Resource -> Response
ReahlWSGIApp -> Response : ""~__call__(environ, start_response)""

@enduml
