' Copyright 2017, 2018, 2022 Reahl Software Services (Pty) Ltd. All rights reserved.

@startuml
!include ../../../../base.iuml

title Serving frontend library static resources

WebConfig -down- LibraryIndex : frontend_libraries >
LibraryIndex -down- "*" Library

LibraryIndex -right- ReahlWSGIApplication
LibraryIndex -- "*" FileOnDisk : packaged_files

ReahlWSGIApplication -right- StaticUI : reahl_static_files
StaticUI -right- FileList
FileOnDisk "*" -- FileList
FileFactory <|-- FileList

@enduml
