' Copyright 2017, 2018, 2022 Reahl Software Services (Pty) Ltd. All rights reserved.

@startuml
!include ../../../../base.iuml

title Shipped files

class "..." as other_classes
Library -right- "*" FileOnDisk : packaged_files
FileOnDisk <|-- ConcatenatedFile
FileOnDisk <|-- PackagedFile
ConcatenatedFile -right- "*" PackagedFile

Library <|-- Bootstrap4
Library <|.. other_classes


@enduml
