@startuml


title ReahlWSGIApplication definition and Request handling

hide members
hide circle

note as N1
This shows:
- Threading/Request/Context scope
- Definition of ReahlWSGIApplication
  by means of Factories
- Each Request is handled by a Resource
  (of differing complexity)
end note

package "This is per process" {

class ReahlWSGIApplication #red
class UserInterfaceFactory  #red
ReahlWSGIApplication -right- UserInterfaceFactory :  root_user_interface_factory
UserInterfaceFactory -right- ViewFactory
}

package "This is per Request(except UserSession)" {

class UserInterface #red
class UserInterfaceFactory
class UserInterfaceFactory_ #red

UserInterfaceFactory <|---- UserInterface
UserInterfaceFactory_ -up--- UserInterface : < sub_ui's

Resource <|-- ComposedPage
Resource <|-- SubResource

UserInterface -down-- "*" SubResource : sub_resources\n {url} >

WebExecutionContext -down- Resource

class Request <<webob.Request>>
class UserSession <<persisted>>
note top of UserSession : ~spans many requests

UserSession -left- WebExecutionContext
Request -up- WebExecutionContext

}


@enduml