' Copyright 2017, 2018, 2022 Reahl Software Services (Pty) Ltd. All rights reserved.

@startuml
!include ../../../base.iuml

title Dependency Injection

component "reahl-web-declarative" as rwd{
	interface "WebUserSession" as WebUserSession
	interface "UserInput" as UserInput
	interface "PersistedException" as PersistedException
	interface "PersistedFile" as PersistedFile
}

component "reahl-web" as rw{
	WebUserSession )-- rw: session_class
	UserInput )-- rw: persisted_userinput_class
	PersistedException )-- rw: persisted_exception_class
	PersistedFile )-- rw: persisted_file_class
}

component "reahl-domain" as rd

rwd ..> rd


@enduml
