' Copyright 2017, 2018, 2022 Reahl Software Services (Pty) Ltd. All rights reserved.

@startuml
!include ../../../base.iuml

title Dependency Injection

Address "*" -right- "1" AddressBook

AddressBook "1" -right- "1" EmailAndPasswordSystemAccount : owner

AddressBook "*" -right- "*" EmailAndPasswordSystemAccount
(AddressBook, EmailAndPasswordSystemAccount) .. Collaborator



@enduml
