@startuml
!include base.iuml


@startsalt
{

<b>Address Book</b>: johndoe@some.org
.
{+
.
<u>Add Address</u>|.|<u>Add Collaborator</u>
.
}
.

{
friend@some.org | [Edit]

friend2@some.org | [Edit]
}

}
@endsalt



@enduml
