' Copyright 2017, 2018, 2022 Reahl Software Services (Pty) Ltd. All rights reserved.

@startuml
!include ../../../base.iuml

@startsalt
{

<b>Edit Address: friend2@some.org </b>
.
{
Name: | "      "
Email: | "      "
.
. | [Update]
}

}
@endsalt



@enduml
