' Copyright 2017, 2018, 2022 Reahl Software Services (Pty) Ltd. All rights reserved.

@startuml
!include ../../../base.iuml


@startsalt
{

<b>Address Books</b>
.
{
<u>johndoe@some.org</u>
<u>janedoe@some.org</u>
}

}
@endsalt



@enduml
