' Copyright 2017, 2018, 2022 Reahl Software Services (Pty) Ltd. All rights reserved.

@startuml
!include ../../../../base.iuml

title Files - basics: SimpleFileInput

class python <<object>>
SimpleFileInput -right- FileField
FileField -right- python

@enduml
