' Copyright 2017, 2018, 2022 Reahl Software Services (Pty) Ltd. All rights reserved.

@startuml
!include ../../../../base.iuml

title Forms and exception handling

class UserInput <<Persisted>>
class SessionData <<Persisted>>
class WebUserSession <<Persisted>>
class PersistedException <<Persisted>>


Form .up..|> Widget
Input .up..|> Widget
UserInput -- Input

RemoteMethod .up.|> Resource
EventChannel-up-|> RemoteMethod

Form -left- RemoteMethod : field_validator
Form -- EventChannel : event_channel

Form -right- "*" Input
Form -- "*" UserInput
Form -- PersistedException

SessionData -right- WebUserSession
UserInput --|> SessionData
PersistedException -- SessionData


@enduml
