' Copyright 2017, 2018, 2022 Reahl Software Services (Pty) Ltd. All rights reserved.

@startuml
!include ../../../../base.iuml

title Hash change handler (Ajax)

HTMLElement -up--|> Widget
HTMLElement -right- HashChangeHandler
HashChangeHandler -right- CheckedRemoteMethod
CheckedRemoteMethod --up-|> RemoteMethod
RemoteMethod -right- MethodResult
WidgetResult -up-|> MethodResult
@enduml
