@startuml

title Input and Input composition infrastructure

hide members
hide circle

class "<b>Input</b>" as Input
class "<b>WrappedInput</b>" as WrappedInput
class "<b>PrimitiveInput</b>" as PrimitiveInput
class Field
note right of Input: "{bound_field of all \nInputs is a Field instance,\n except for ButtonInputs,\n which have Events}"

HTMLWidget -up-|> Widget
HTMLElement -up-|> Widget
HTMLWidget -right- HTMLElement : html_representation
Input -up-|> HTMLWidget
Input -left- Field : bound_field >
PrimitiveInput -up-|> Input
WrappedInput -up-|> Input
WrappedInput -- Input

Event -up-|> Field
ButtonInput -left- Event : bound_field >
ButtonInput -up-|> PrimitiveInput
InputTypeInput -up-|> PrimitiveInput
TextArea -up-|> PrimitiveInput
SelectInput -up-|> PrimitiveInput
Option -up-|> PrimitiveInput
RadioButtonSelectInput -up-|> PrimitiveInput
CheckboxSelectInput -up-|> PrimitiveInput
TextInput -up-|> InputTypeInput
SingleChoice -up-|> InputTypeInput

@enduml
