from reahl.doc.examples.howtos.customisingerrorpages.customisingerrorpages import BreakingUIWithBuiltInErrorPage, BreakingUIWithCustomErrorPage

web.site_root = BreakingUIWithCustomErrorPage
#web.site_root = BreakingUIWithBuiltInErrorPage
