# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_wheels:
    runs-on: ubuntu-20.04
    env:
      VENV: ~/.venvs/build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Setup dev env
        run: |
          mkdir -p ~/.reahlworkspace/dist-egg
          mkdir -p ~/.venvs
          sudo -H ./scripts/installBuildDebs.sh
          sudo -H ./scripts/installDebs.sh
          sudo -H ./scripts/installDevEnvDebs.sh
          ./scripts/createVenv.sh $(VENV)

      - name: bootstrap venv
        run: |
          $(VENV)/bin/python scripts/bootstrap.py --script-dependencies
          $(VENV)/bin/python scripts/bootstrap.py --pip-installs

      - name: build wheels
        run:  $(VENV)/bin/reahl build -sdX

      - name: save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-wheels
          path: |
            ~/.reahlworkspace/dist-egg/*
            ls -la ~/.reahlworkspace/dist-egg/*

  test:
    runs-on: ubuntu-20.04
    needs: build_wheels

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: fetch built wheels
        uses: actions/upload-artifact@v2
        with:
          name: dist-wheels

      - name: debug
        run: |
          pwd
          ls -la ~/.reahlworkspace/dist-egg/*

