name: CI

on:
  schedule:
    - cron: '42 15 * * 6'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  call_build:
    uses: ./.github/workflows/build.yml
