# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_wheels:
    runs-on: ubuntu-20.04
    env:
      VENV: ~/.venvs/build
      REAHLWORKSPACE: /home/runner
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Setup dev env
        run: |
          mkdir -p $REAHLWORKSPACE/.reahlworkspace/dist-egg
          mkdir -p ~/.venvs
          sudo -H ./scripts/installBuildDebs.sh
          sudo -H ./scripts/installDebs.sh
          sudo -H ./scripts/installDevEnvDebs.sh
          travis/configurePip.sh
          travis/createTestSshKey.sh
          travis/createTestGpgKey.sh

      - name: bootstrap venv
        run: |
          ./scripts/createVenv.sh $VENV
          source $VENV/bin/activate
          python scripts/bootstrap.py --script-dependencies
          python scripts/bootstrap.py --pip-installs
          reahl list
          echo $REAHLWORKSPACE
          pwd
          ls -la $REAHLWORKSPACE/.reahlworkspace/
          cat $REAHLWORKSPACE/.reahlworkspace/current.selection
          cat $REAHLWORKSPACE/.reahlworkspace/workspace.projects

      - name: build wheels
        run: |
          echo $REAHLWORKSPACE
          pwd
          ls -la $REAHLWORKSPACE/.reahlworkspace/
          cat $REAHLWORKSPACE/.reahlworkspace/current.selection
          cat $REAHLWORKSPACE/.reahlworkspace/workspace.projects
          source $VENV/bin/activate
          reahl list
          reahl build -sdX || (EXITCODE=$?; shred -f $HOME/.gnupg/*; exit $EXITCODE)

      - name: save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-wheels
          path: |
            $REAHLWORKSPACE/.reahlworkspace/dist-egg/*
            ls -la $REAHLWORKSPACE/.reahlworkspace/dist-egg/*

  test:
    runs-on: ubuntu-20.04
    needs: build_wheels

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: fetch built wheels
        uses: actions/upload-artifact@v2
        with:
          name: dist-wheels

      - name: debug
        run: |
          pwd
          ls -la $REAHLWORKSPACE/.reahlworkspace/dist-egg/*

