# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:12.3
        env:
          POSTGRES_USER: reahl
          POSTGRES_PASSWORD: reahl
          POSTGRES_DB: reahl
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5


    strategy:
      matrix:
        os: [ubuntu-20.04]
        #python-version: ['3.6', '3.7', '3.8']
        python-version: ['3.6']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install Basic apt dependencies
        run: sudo apt-get install openssh-client dpkg-dev bzr git firefox firefox-geckodriver

      - name: Install For compiling pip installed extensions we use
        run: sudo apt-get install  python3-virtualenv python-dev gcc cython libxml2-dev libxslt-dev libsqlite3-0 sqlite3 postgresql-server-dev-all zlib1g-dev libjpeg62-dev libfreetype6-dev liblcms2-dev libmysqlclient-dev

        # - phantomjs  # for reference... not allowed in apt addon
      - name: Install For testing of reahl-component
        run: sudo apt-get install graphviz

      - name: Debug info
        run: |
          git --version
          firefox --version
          geckodriver --version
          gpg --version

      - name: Run tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: echo Tests wil run with xvfb enabled!

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
