# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build development docker image
        run: docker build -t reahl-dev:snapshot -f Dockerfile .

  build_wheels:
    needs: build_image
    runs-on: ubuntu-20.04
#    container:
#      image: reahl-dev:snapshot

    steps:
      - uses: actions/checkout@v2
      - name: Debug output
        run: |
          docker image ls
          pwd
          ls -la
          whoami
          ps auxwww


